# sudo docker build -t msdemo/pydjango .

#  BASE IMAGE
FROM python:3.7

# AUTHOR/ MAINTAINER
MAINTAINER raunak-r

# COPY THE MAIN CODE FOLDER INSIDE THE CONTAINER
ADD . /app

# SET THE DEFAULT DIRECTORY FOR CMD TO EXECUTE COMMANDS
WORKDIR /app

# INSTALL BACKEND DEPENDENCIES
RUN pip install -r ./requirements.txt

# RUN THE DJANGO APP
EXPOSE 8000
RUN python ./manage.py migrate
CMD [ "python", "./manage.py", "runserver", "0.0.0.0:8000" ]